config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :questions

  resources :comments

  resources :answers

  resources :sessions

  root :to => 'users#new'

  get 'log_in' => 'sessions#new', :as => :'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get 'logged_in' => 'sessions#index', :as => 'logged_in'
  get 'invalid' => 'sessions#show', :as => 'invalid'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # @param [Object] password

# @param [Object] username
def self.authenticate(username, password)
  #return 1
  user2 = find_by_username(username)
  u = find_by_password(password)
  puts user2

 if user2  && (user2 == u)
   return 1
 else
   return false
 end




end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new

  end
  def show

  end
  def create
    @answer = Answer.new(params.require(:answer).permit(:answer, :ansid))

    @answer.save
    redirect_to @answer

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @comment = Comment.find(params[:comment_id])
      @comment = @comment.comments.create(comment_params)
      redirect_to comment_path(@comment)
    end

    private
    def comment_params
      params.require(:comment).permit(:comment, :qid, :ansid)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.all
  end
  def show
    @question = Question.find(params[:id])

  #  some other code
  end
  def new

  end

  def create
    @question = Question.new(params.require(:question).permit(:ques, :qid))

    @question.save
    redirect_to @question
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def create
  a = params[:username]
  puts a
  b = params[:password]
  puts b

  user = User.authenticate(params[:username], params[:password])
  if user
 #session[:user_id] = user.id
      redirect_to logged_in_url
  else
    redirect_to invalid_url
  end
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/new.html.erb
<%= form_for :answer, url: answers_path do |f| %>
    <p>
      <%= f.label :answer %><br>
      <%= f.text_area :answer %>
    </p>

    <p>
      <%= f.label :ansid %><br>
      <%= f.text_field :ansid %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/answers/show.html.erb
<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<p>
  <strong>id:</strong>
  <%= @answer.ansid %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @question.each do |q| %>
      <tr>
        <td><%= q.ques %></td>
        <td><%= q.qid %></td>
        <td><%= link_to 'Show', question_path(q) %></td>
      </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<%= form_for :question, url: questions_path do |f| %>
    <p>
      <%= f.label :question %><br>
      <%= f.text_area :ques %>
    </p>

    <p>
      <%= f.label :qid %><br>
      <%= f.text_field :qid %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/questions/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @question.ques %>
</p>

<p>
  <strong>id:</strong>
  <%= @question.qid %>
</p>

<% if false %>
<h2>Comments</h2>
<% @question.comments.each do |comment| %>
    <p>
      <strong>comment:</strong>
      <%= comment.comment %>
    </p>

    <p>
      <strong>qid:</strong>
      <%= comment.qid %>
    </p>
    <p>
      <strong>ansid:</strong>
      <%= comment.ansid %>
    </p>
<% end %>


<h2>Add a comment:</h2>
<%= form_for @question do |f| %>
    <p>
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </p>
    <p>
      <%= f.label :questionid %><br>
      <%= f.text_field :qid %>
    </p>
    <p>
      <%= f.label :anserid %><br>
      <%= f.text_field :ansid %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>